### ISSUE TITLE
Adding ppc64le support for infinispan

### ISSUE THREAD

**Issue by rashmi-ibm** [infinispan/infinispan-maven-plugins#3]
Need info on how to generate platform specific protolock file on a specific architecture.
I tried to build the infinispan-maven-plugins repo on the desired architecture and was able to build it successfully.

But I need inputs on how to generate the protolock file as it has to be present in the below directory.
/infinispan-maven-plugins/tree/bb4db173c38cc08aadb994f728d0e4f87e5e98c2/proto-schema-compatibility/src/main/resources/

**Comment by anistor** [comment]
Protolock is a different project, not part of Indinidspan. Here it is: https://github.com/nilslice/protolock

It has releases for several architectures but not for ppc64le. I'm not sure, are you asking about build instructions?  Maybe the author of protolock could help.

**Comment by rashmi-ibm** [comment]
The protolock file placed in below folder is obtained by building repository: https://github.com/nilslice/protolock on linux-x86_64 server.
Folder: https://github.com/infinispan/infinispan-maven-plugins/tree/master/proto-schema-compatibility/src/main/resources/linux-x86_64

**Comment by tristantarrant** [comment]
I don't think we need to run the proto compatibility stuff every time, as long as it is done at release time (on an x86_64 box). We can probably skip running this on non-x86_64 platforms, @ryanemerson  ?

**Comment by rashmi-ibm** [comment]
I was trying to build infinispan repo: https://github.com/infinispan/infinispan on ppc64le system got the below error

error:-
[INFO] Infinispan Protostuff Marshaller Bridge ............ SKIPPED
[INFO] Infinispan Protostuff Marshaller Bridge Bundle ..... SKIPPED
[INFO] Infinispan Hibernate 5.1 Cache ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.824 s
[INFO] Finished at: 2019-11-01T10:46:39Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.infinispan.maven-plugins:proto-schema-compatibility:1.0.1.Final:proto-schema-compatibility-check (default) on project infinispan-commons: OS not supported. Unable to find a protolock binary for the classifier linux-ppcle_64 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :infinispan-commons

The error was thrown from infinispan-maven-plugins jar as the file protolock was not present for linux-ppc64le architecture.

**Comment by ryanemerson** [comment]
@rashmi-ibm That error is expected as there isn't a `protolock` binary for ppc64le. I agree with @tristantarrant though, I don't think it's necessary for this plugin to be executed on every architecture. The important thing is that we check compatiblity at release time via Jenkins.

**Comment by rashmi-ibm** [comment]
Thanks @ryanemerson @tristantarrant. So for now I will try to exclude the plugin in my local repo and try building infinispan.

**Comment by rashmi-ibm** [comment]
@ryanemerson I am getting the below error while trying to run the unit tests for "Wildfly Module Integration Tests"

Is it trying to deploy the war in a running docker container? Pointers around the same would be great.

[INFO] Running org.infinispan.test.integration.as.InfinispanExtensionIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.755 s <<< FAILURE! - in org.infinispan.test.integration.as.InfinispanExtensionIT
[ERROR] org.infinispan.test.integration.as.InfinispanExtensionIT  Time elapsed: 0.001 s  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Cannot deploy dep1.war: WFLYCTL0063: Composite operation was rolled back

**Comment by ryanemerson** [comment]
@rashmi-ibm That error should be fixed by this commit (https://github.com/infinispan/infinispan/commit/fd6f5753b7a26ee75863bce2aac0cb59b5b63c3d) on master, please pull the latest changes and try. 

Thank you for contributing, but the above error is not related to the `infinispan-maven-plugins` though, so in the future please report unrelated errors via https://issues.jboss.org/ or via Zulip https://infinispan.zulipchat.com/.

**Comment by rashmi-ibm** [comment]
Thanks @ryanemerson . I pulled the above change and that sorted out my issue. I however have multiple issues related to Arquillian failures and some other failures for infinispan will try to reach out on zulipchat for those.
